#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#
seglcd-configurator config device-configurator config_ezpd ez-pd-configurator smartio-configurator dfuh-tool modlibs library-manager config_usbdev usbdev-configurator bsp-assistant qspi-configurator :
	make -C LVDS_USB_Stream $@

config_bt bt-configurator config_lin lin-configurator :
	$(error $@ configurator cannot be executed at the application level. Run this command from the desired project directory.)

.PHONY: seglcd-configurator config device-configurator config_ezpd ez-pd-configurator config_bt bt-configurator smartio-configurator dfuh-tool modlibs library-manager config_lin lin-configurator config_usbdev usbdev-configurator bsp-assistant qspi-configurator
