#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#
# Path to the current BSP
SEARCH_TARGET_APP_QUAD_FX10=bsps/TARGET_APP_QUAD_FX10

# The search paths for the included middleware
SEARCH_freertos=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/freertos/release-v10.6.202
SEARCH_usbfxstack=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/usbfxstack/release-v1.3.3
SEARCH_abstraction-rtos=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/abstraction-rtos/release-v1.13.0
SEARCH_cat1cm0p=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/cat1cm0p/release-v1.11.0
SEARCH_clib-support=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/clib-support/release-v1.8.0
SEARCH_cmsis=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/cmsis/release-v6.1.0
SEARCH_core-lib=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/core-lib/release-v1.7.0
SEARCH_core-make=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/core-make/release-v3.9.0
SEARCH_mtb-pdl-cat1=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/mtb-pdl-cat1/release-v3.23.0
SEARCH_recipe-make-cat1a=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/recipe-make-cat1a/release-v2.7.0

# Search libraries added to build
SEARCH_MTB_MK+=$(SEARCH_freertos)
SEARCH_MTB_MK+=$(SEARCH_usbfxstack)
SEARCH_MTB_MK+=$(SEARCH_abstraction-rtos)
SEARCH_MTB_MK+=$(SEARCH_cat1cm0p)
SEARCH_MTB_MK+=$(SEARCH_clib-support)
SEARCH_MTB_MK+=$(SEARCH_cmsis)
SEARCH_MTB_MK+=$(SEARCH_core-lib)
SEARCH_MTB_MK+=$(SEARCH_core-make)
SEARCH_MTB_MK+=$(SEARCH_mtb-pdl-cat1)
SEARCH_MTB_MK+=$(SEARCH_recipe-make-cat1a)

-include $(CY_INTERNAL_APP_PATH)/importedbsp.mk
COMPONENTS += MW_FREERTOS
COMPONENTS += MW_USBFXSTACK
COMPONENTS += MW_ABSTRACTION_RTOS
COMPONENTS += MW_CAT1CM0P
COMPONENTS += MW_CLIB_SUPPORT
COMPONENTS += MW_CMSIS
COMPONENTS += MW_CORE_LIB
COMPONENTS += MW_CORE_MAKE
COMPONENTS += MW_MTB_PDL_CAT1
COMPONENTS += MW_RECIPE_MAKE_CAT1A

# Register map file
DEVICE_CYUSB4024-BZXI_SVD=$(SEARCH_mtb-pdl-cat1)/devices/COMPONENT_CAT1A/svd/fx3g2.svd


#
# generate make targets for the graphical editors that are specific to this project
#

config:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name device-configurator
.PHONY: config

CY_HELP_config=Launches the Device Configurator 5.70 GUI for the target's modus file
CY_HELP_config_VERBOSE=Launches the Device Configurator 5.70 GUI. Check the Device Configurator 5.70 User Guide for more information.
mtb_help_tool_config:
	@:
	$(info $(MTB__SPACE)config              $(CY_HELP_config))

mtb_help_tools_end: mtb_help_tool_config
mtb_help_tool_config: mtb_help_tools_start
.PHONY: mtb_help_tool_config

device-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name device-configurator
.PHONY: device-configurator

CY_HELP_device-configurator=Launches the Device Configurator 5.70 GUI for the target's modus file
CY_HELP_device-configurator_VERBOSE=Launches the Device Configurator 5.70 GUI. Check the Device Configurator 5.70 User Guide for more information.
mtb_help_tool_device-configurator:
	@:
	$(info $(MTB__SPACE)device-configurator $(CY_HELP_device-configurator))

mtb_help_tools_end: mtb_help_tool_device-configurator
mtb_help_tool_device-configurator: mtb_help_tools_start
.PHONY: mtb_help_tool_device-configurator

modlibs:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name library-manager
.PHONY: modlibs

CY_HELP_modlibs=Launches the Library Manager 2.70 GUI
CY_HELP_modlibs_VERBOSE=Launches the Library Manager 2.70 GUI. Check the Library Manager 2.70 User Guide for more information.
mtb_help_tool_modlibs:
	@:
	$(info $(MTB__SPACE)modlibs             $(CY_HELP_modlibs))

mtb_help_tools_end: mtb_help_tool_modlibs
mtb_help_tool_modlibs: mtb_help_tools_start
.PHONY: mtb_help_tool_modlibs

library-manager:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name library-manager
.PHONY: library-manager

CY_HELP_library-manager=Launches the Library Manager 2.70 GUI
CY_HELP_library-manager_VERBOSE=Launches the Library Manager 2.70 GUI. Check the Library Manager 2.70 User Guide for more information.
mtb_help_tool_library-manager:
	@:
	$(info $(MTB__SPACE)library-manager     $(CY_HELP_library-manager))

mtb_help_tools_end: mtb_help_tool_library-manager
mtb_help_tool_library-manager: mtb_help_tools_start
.PHONY: mtb_help_tool_library-manager

config_lin:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name lin-configurator
.PHONY: config_lin

CY_HELP_config_lin=Launches the LIN Configurator 1.90 GUI for the target's mtblin file
CY_HELP_config_lin_VERBOSE=Launches the LIN Configurator 1.90 GUI. Check the LIN Configurator 1.90 User Guide for more information.
mtb_help_tool_config_lin:
	@:
	$(info $(MTB__SPACE)config_lin          $(CY_HELP_config_lin))

mtb_help_tools_end: mtb_help_tool_config_lin
mtb_help_tool_config_lin: mtb_help_tools_start
.PHONY: mtb_help_tool_config_lin

lin-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name lin-configurator
.PHONY: lin-configurator

CY_HELP_lin-configurator=Launches the LIN Configurator 1.90 GUI for the target's mtblin file
CY_HELP_lin-configurator_VERBOSE=Launches the LIN Configurator 1.90 GUI. Check the LIN Configurator 1.90 User Guide for more information.
mtb_help_tool_lin-configurator:
	@:
	$(info $(MTB__SPACE)lin-configurator    $(CY_HELP_lin-configurator))

mtb_help_tools_end: mtb_help_tool_lin-configurator
mtb_help_tool_lin-configurator: mtb_help_tools_start
.PHONY: mtb_help_tool_lin-configurator

config_usbdev:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name usbdev-configurator
.PHONY: config_usbdev

CY_HELP_config_usbdev=Launches the USB Configurator [for USBDEV middleware] 3.20 GUI for the target's cyusbdev file
CY_HELP_config_usbdev_VERBOSE=Launches the USB Configurator [for USBDEV middleware] 3.20 GUI. Check the USB Configurator [for USBDEV middleware] 3.20 User Guide for more information.
mtb_help_tool_config_usbdev:
	@:
	$(info $(MTB__SPACE)config_usbdev       $(CY_HELP_config_usbdev))

mtb_help_tools_end: mtb_help_tool_config_usbdev
mtb_help_tool_config_usbdev: mtb_help_tools_start
.PHONY: mtb_help_tool_config_usbdev

usbdev-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name usbdev-configurator
.PHONY: usbdev-configurator

CY_HELP_usbdev-configurator=Launches the USB Configurator [for USBDEV middleware] 3.20 GUI for the target's cyusbdev file
CY_HELP_usbdev-configurator_VERBOSE=Launches the USB Configurator [for USBDEV middleware] 3.20 GUI. Check the USB Configurator [for USBDEV middleware] 3.20 User Guide for more information.
mtb_help_tool_usbdev-configurator:
	@:
	$(info $(MTB__SPACE)usbdev-configurator $(CY_HELP_usbdev-configurator))

mtb_help_tools_end: mtb_help_tool_usbdev-configurator
mtb_help_tool_usbdev-configurator: mtb_help_tools_start
.PHONY: mtb_help_tool_usbdev-configurator

bsp-assistant:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name bsp-assistant
.PHONY: bsp-assistant

CY_HELP_bsp-assistant=Launches the BSP Assistant 1.70 GUI
CY_HELP_bsp-assistant_VERBOSE=Launches the BSP Assistant 1.70 GUI. Check the BSP Assistant 1.70 User Guide for more information.
mtb_help_tool_bsp-assistant:
	@:
	$(info $(MTB__SPACE)bsp-assistant       $(CY_HELP_bsp-assistant))

mtb_help_tools_end: mtb_help_tool_bsp-assistant
mtb_help_tool_bsp-assistant: mtb_help_tools_start
.PHONY: mtb_help_tool_bsp-assistant

qspi-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name qspi-configurator
.PHONY: qspi-configurator

CY_HELP_qspi-configurator=Launches the QSPI Configurator 4.80 GUI for the target's cyqspi file
CY_HELP_qspi-configurator_VERBOSE=Launches the QSPI Configurator 4.80 GUI. Check the QSPI Configurator 4.80 User Guide for more information.
mtb_help_tool_qspi-configurator:
	@:
	$(info $(MTB__SPACE)qspi-configurator   $(CY_HELP_qspi-configurator))

mtb_help_tools_end: mtb_help_tool_qspi-configurator
mtb_help_tool_qspi-configurator: mtb_help_tools_start
.PHONY: mtb_help_tool_qspi-configurator

.PHONY: mtb_help_tools_start mtb_help_tools_end
